# Generated by Django 4.2.7 on 2023-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoples',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
